package com.quarkus.gatelink.system;

import jakarta.json.JsonObject;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

/**
 * Type-safe HTTP contract used by GateLink system tests.
 *
 * The implementation is generated by Quarkus' MicroProfile REST Client.
 */
@Path("/")
public interface GateLinkApi {

    @GET
    @Path("keys/public")
    @Produces(MediaType.TEXT_PLAIN)
    Response publicKey();

    @POST
    @Path("subscriptions")
    @Consumes(MediaType.APPLICATION_JSON)
    Response subscribe(JsonObject subscription);

    @GET
    @Path("subscriptions")
    @Produces(MediaType.APPLICATION_JSON)
    Response subscriptions();

    @DELETE
    @Path("subscriptions/{endpoint}")
    Response unsubscribe(@PathParam("endpoint") String encodedEndpoint);

    @DELETE
    @Path("subscriptions")
    Response removeAllSubscriptions();

    @POST
    @Path("notifications")
    @Consumes(MediaType.TEXT_PLAIN)
    Response sendNotification(String message);

    @GET
    @Path("q/health")
    @Produces(MediaType.APPLICATION_JSON)
    Response health();
}
